name = "landing-form-worker"
main = "worker.js"
compatibility_date = "2026-02-01"
account_id = "6b89326ea596b319412c91de7732e405"
workers_dev = true

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "278556b37c6f49a894edab60a7a96d92"

# Secrets (set via wrangler secret put):
# TELEGRAM_BOT_TOKEN
# TELEGRAM_CHAT_ID
# APPS_SCRIPT_URL

# Custom domain (set up in Cloudflare Dashboard):
# landing-form.webwerkstatt-nord.de â†’ this worker

# [vars]
# ENVIRONMENT = "production"
